### ISSUE TITLE
Task ID bug

### ISSUE THREAD

**Issue by heybran** [heybran/cli-todo-app#9]
When listing tasks that belong to specific category or complete status, tasks IDs starts from 1 again, did not match with their original IDs, which will cause unexpected result if users try to delete tasks based on the IDs provided by `list` subcommand.

**Comment by priya1011** [comment]
@heybran I would like to take on this issue, I will create a pull request with the changes once I have completed the implementation. Looking forward to contributing to the project!

**Comment by heybran** [comment]
Sure thing @priya1011, that'd be great! Looking forward to your improvement on this project.

**Comment by priya1011** [comment]
I think we should use [UUID](https://pkg.go.dev/github.com/google/UUID#New) provided by Golang as task Ids. WDYT @heybran?

**Comment by priya1011** [comment]
Hi @heybran,

After reviewing the code, I noticed that the issue arises from not storing unique IDs for the tasks. Currently, the code uses an  [iterator](https://github.com/heybran/gtodo/blob/main/todo/todo.go#L173) over the JSON items to display the IDs, resulting in them starting from 1 and incrementing up to the length of the tasks.

To address this issue, I would recommend using the [UUID](https://pkg.go.dev/github.com/google/UUID#New) provided by Golang as task IDs. By implementing UUIDs, we can guarantee that each task will have a globally unique identifier. WDYT?

**Comment by heybran** [comment]
Hi @priya1011,

`UUID` sounds good. Although from users perspective, at the moment deleting a task is quite easy by just running `gtodo delete -id 5`, once we've added `UUID`, what will it looks like, as I guess the ID will be a bit longer in length? 

If I list all the existing tasks by run `gtodo list`, mine prints:

<img width="1242" alt="Screenshot 2023-06-03 at 22 32 01" src="https://github.com/heybran/gtodo/assets/75633537/cb01d171-194e-4f6b-9e76-b45601d9b071">

Here, I can delete task with id of `22` by `gtodo delete -id 22`.

But if only list tasks that are under `Project` category, mine prints:

<img width="1242" alt="Screenshot 2023-06-03 at 22 32 25" src="https://github.com/heybran/gtodo/assets/75633537/6f9abfed-c2cb-4c4d-a051-8b3681a66638">

If I run `gtodo detele -id 1`, it won't delete the one I intend to, it just delete the very first one stored in the JSON file. It's caused by this code block I think: https://github.com/heybran/gtodo/blob/main/todo/todo.go#LL173C2-L173C2

Alternatively I was thinking, after running the 2nd command we list the 2 `Project` tasks by id of their original IDs in the JSON file, meaning `21` and `22`, so we can safely delete it by running `gtodo list -id 21`.  Which way sounds better to you? If `UUID` looks more solid to you, please go for it and I'm sure I will learn a lot from your solution :)

**Comment by priya1011** [comment]
Yes, you're correct. 
UUIDs can be long and not very user-friendly. To address this issue and provide a more desired type of ID, I have added the `ID` field to the `item` struct. This approach allows for the use of unique IDs that are easier for users to work with. 
However, please note as we introduce the `ID` field to an existing set of items, IDs will all be initialized to 0 of those. As a result, updating or deleting items may affect the first item in the list with an ID of 0. To resolve this, you may need to generate a new `.todos.json` file or modify the existing items manually to assign unique IDs to each item.

**Comment by heybran** [comment]
Thanks @priya1011, works like a charm.
